// Grafo fijo de la planta 1 bajo ?qa=1 -- derivado de la semilla 4141891232
// del 'Telar de Mazmorras' (artefacto de disenio de mazmorras). Generado una
// sola vez offline (BSP+CA de la semilla -> grafo de 29 salas conectadas
// -> incrustado aqui como datos estaticos, sin aleatoriedad) -- ver
// generarGrafoPlantaSemilla1() en floorgen.js, que lo consume.
export const SEED1_ROOMS = [{"id":0,"gx":1,"gy":6,"esInicial":true,"esFinal":false},{"id":1,"gx":2,"gy":6,"esInicial":false,"esFinal":false},{"id":2,"gx":0,"gy":7,"esInicial":false,"esFinal":false},{"id":3,"gx":1,"gy":7,"esInicial":false,"esFinal":false},{"id":4,"gx":0,"gy":6,"esInicial":false,"esFinal":false},{"id":5,"gx":0,"gy":5,"esInicial":false,"esFinal":false},{"id":6,"gx":1,"gy":5,"esInicial":false,"esFinal":false},{"id":7,"gx":2,"gy":5,"esInicial":false,"esFinal":false},{"id":8,"gx":0,"gy":9,"esInicial":false,"esFinal":false},{"id":9,"gx":0,"gy":10,"esInicial":false,"esFinal":false},{"id":10,"gx":1,"gy":8,"esInicial":false,"esFinal":false},{"id":11,"gx":1,"gy":9,"esInicial":false,"esFinal":false},{"id":12,"gx":1,"gy":3,"esInicial":false,"esFinal":false},{"id":13,"gx":1,"gy":2,"esInicial":false,"esFinal":false},{"id":14,"gx":1,"gy":4,"esInicial":false,"esFinal":false},{"id":15,"gx":0,"gy":4,"esInicial":false,"esFinal":false},{"id":16,"gx":2,"gy":1,"esInicial":false,"esFinal":false},{"id":17,"gx":2,"gy":0,"esInicial":false,"esFinal":false},{"id":18,"gx":3,"gy":0,"esInicial":false,"esFinal":true},{"id":19,"gx":2,"gy":4,"esInicial":false,"esFinal":false},{"id":20,"gx":3,"gy":4,"esInicial":false,"esFinal":false},{"id":21,"gx":3,"gy":5,"esInicial":false,"esFinal":false},{"id":22,"gx":3,"gy":6,"esInicial":false,"esFinal":false},{"id":23,"gx":2,"gy":2,"esInicial":false,"esFinal":false},{"id":24,"gx":3,"gy":2,"esInicial":false,"esFinal":false},{"id":25,"gx":2,"gy":3,"esInicial":false,"esFinal":false},{"id":26,"gx":4,"gy":3,"esInicial":false,"esFinal":false},{"id":27,"gx":4,"gy":4,"esInicial":false,"esFinal":false},{"id":28,"gx":3,"gy":3,"esInicial":false,"esFinal":false}];

// dir es la direccion de la puerta vista DESDE la sala `a` hacia `b`.
export const SEED1_EDGES = [{"a":0,"dir":"E","b":1},{"a":0,"dir":"S","b":3},{"a":0,"dir":"N","b":6},{"a":2,"dir":"E","b":3},{"a":3,"dir":"S","b":10},{"a":4,"dir":"N","b":5},{"a":5,"dir":"E","b":6},{"a":6,"dir":"E","b":7},{"a":6,"dir":"N","b":14},{"a":8,"dir":"E","b":11},{"a":8,"dir":"S","b":9},{"a":10,"dir":"S","b":11},{"a":12,"dir":"S","b":14},{"a":12,"dir":"N","b":13},{"a":14,"dir":"O","b":15},{"a":14,"dir":"E","b":19},{"a":16,"dir":"S","b":23},{"a":16,"dir":"N","b":17},{"a":17,"dir":"E","b":18},{"a":19,"dir":"E","b":20},{"a":19,"dir":"N","b":25},{"a":20,"dir":"S","b":21},{"a":21,"dir":"S","b":22},{"a":23,"dir":"S","b":25},{"a":23,"dir":"E","b":24},{"a":25,"dir":"E","b":28},{"a":26,"dir":"O","b":28},{"a":26,"dir":"S","b":27}];
